### ISSUE TITLE
YAML-1.26_001: "Error parsing output from CPAN::Reporter::PrereqCheck" on Strawberry Perl

### ISSUE THREAD

**Issue by twata1** [ingydotnet/yaml-pm#210] opened 2018-10-20 15:18 UTC
Hi,

I was at a loss which way I should report to 
[YAML issues](https://github.com/ingydotnet/yaml-pm/issues)
or
[CPAN-Reporter issues](https://github.com/cpan-testers/CPAN-Reporter/issues) .

It seems to occur only in YAML-1.26_001, so I report it here.

Running Strawberry Perl 5.16.3 32 bit, I noticed the following message.

```C:\home\picture>cpan TINITA/YAML-1.26_001.tar.gz```

(snip)
```
All tests successful.
Files=54, Tests=541, 59 wallclock secs ( 0.61 usr +  0.38 sys =  0.98 CPU)
Result: PASS
(C:\Strawberry\c\bin\dmake.exe test exited with 0)
Error parsing output from CPAN::Reporter::PrereqCheck:
1..0CPAN::Reporter: Test result is 'pass', All tests successful.
CPAN::Reporter: preparing a CPAN Testers report for YAML-1.26_001
CPAN::Reporter: sending test report with 'pass' via Metabase
  TINITA/YAML-1.26_001.tar.gz
  C:\Strawberry\c\bin\dmake.exe test -- OK
Running make install
```
(snip)

Thank you,

**Comment by perlpunk** [comment] 2018-10-28 19:14
Thanks.
Do you have any more information on this? Or how I can reproduce it without sending an actual report?
I can't really see the failure, the error message is not from YAML.pm

**Comment by twata1** [comment] 2018-10-29 13:50
Thank you for your reply.

> Do you have any more information on this?

[This  CPAN Testers Report](http://www.cpantesters.org/cpan/report/a4bde7ba-6d2a-1014-8e93-a41d032c038b)

That's about it.

Sorry for the lack of information .
Although it may take time or I don't know if I can identify the cause, I will investigate the issue.

Thank you,

**Comment by twata1** [comment] 2018-11-03 09:35
It seems to me that it occurs when a line containing "Test::YAML" is passed to CPAN::Reporter::PrereqCheck.
I'm attaching sample files.
[prereqchk.pl.txt](https://github.com/ingydotnet/yaml-pm/files/2544820/prereqchk.pl.txt)
[list1.txt](https://github.com/ingydotnet/yaml-pm/files/2544821/list1.txt)
[list2.txt](https://github.com/ingydotnet/yaml-pm/files/2544822/list2.txt)

The execution result is as follows.

```
C:\home\picture>prereqchk.pl list1.txt
Can't determine section names at C:\home\picture\perl5\lib\perl5/CPAN/Reporter/PrereqCheck.pm line 0.
END failed--call queue aborted, <DATA> line 1.
Test::YAML 1 1.07
Encode 1 2.49
Test::Deep 1 1.128
ExtUtils::MakeMaker 1 7.34
Test::More 1 1.302140
1..0

C:\home\picture>prereqchk.pl list2.txt
Encode 1 2.49
Test::Deep 1 1.128
ExtUtils::MakeMaker 1 7.34
Test::More 1 1.302140

C:\home\picture>
```

**Comment by twata1** [comment] 2018-11-03 12:07
[Additional Information]

```
C:\home\picture>ack "Can't determine section names"
perl5\lib\perl5\Test\Base.pm
287:my $name_error = "Can't determine section names";

C:\home\picture>perl -MTest::Base -e "print $Test::Base::VERSION"
0.89
C:\home\picture>
```

**Comment by perlpunk** [comment] 2018-11-03 12:46
Thanks! It seems this is related to a previous issue https://github.com/ingydotnet/test-yaml-pm/issues/3 in Test::Base. So my fix https://github.com/ingydotnet/test-base-pm/pull/21 wasn't sufficient.

**Comment by perlpunk** [comment] 2018-11-03 16:53
I created https://github.com/ingydotnet/test-base-pm/issues/22. Since it has nothing to do with YAML.m itself I'm closing this.

**Closed by perlpunk** 2018-11-03 16:53 UTC
