### ISSUE TITLE
YAML depends on YAML, so can/does not install.

### ISSUE THREAD

**Issue by gitcnd** [ingydotnet/yaml-pm#218] opened 2019-06-28 06:30 UTC
Can't install YAML, because it needs itself to install:-

[root@YAML-1.29-0ddltx]# perl Makefile.PL       
Checking if your kit is complete...
Looks good
Warning: prerequisite Test::Deep 0 not found.
Warning: prerequisite Test::YAML 1.05 not found. We have 0.80.
CPAN::Meta::YAML 0.011 is not available
 at /usr/share/perl5/CPAN/Meta.pm line 615
[root@YAML-1.29-0ddltx]# dir Makefile
ls: cannot access Makefile: No such file or directory

[root@CPAN-Meta-YAML-0.018-rScHf0]# perl Makefile.PL 
Checking if your kit is complete...
Looks good
CPAN::Meta::YAML 0.011 is not available
 at /usr/share/perl5/CPAN/Meta.pm line 615
[root@CPAN-Meta-YAML-0.018-rScHf0]# dir Makefile
ls: cannot access Makefile: No such file or directory

You need to stop using "cutting edge" build tools for the basic building blocks of the perl system, because it just keeps breaking everything...  You don't need all that modern cruft - just do it the old way - that worked fine.

**Comment by perlpunk** [comment] 2019-06-28 08:31
Which perl version and platform are you on?

I can't reproduce that on linux perl 5.12.5.

Also, from your output it seems that YAML.pm depends on CPAN::Meta::YAML, and CPAN::Meta::YAML depends on itself, so it's an issue of CPAN::Meta::YAML, not YAML.pm.

**Comment by perlpunk** [comment] 2019-06-28 08:36
```
/tmp% perl -v

This is perl 5, version 12, subversion 5 (v5.12.5) built for x86_64-linux
[...]
/tmp% perl -wE'use CPAN::Meta::YAML'
Can't locate CPAN/Meta/YAML.pm in @INC...

/tmp/CPAN-Meta-YAML-0.018% perl Makefile.PL
Checking if your kit is complete...
Looks good
Warning: prerequisite JSON::PP 0 not found.
Writing Makefile for CPAN::Meta::YAML
```

**Comment by haarg** [comment] 2019-06-28 09:21
It looks like somehow you have gotten CPAN::Meta installed, but not its prerequisites.  This ends up breaking ExtUtils::MakeMaker.  Removing and then reinstalling CPAN::Meta should solve the issue.

**Comment by perlpunk** [comment] 2020-05-30 11:34
Closing, no feedback

**Closed by perlpunk** 2020-05-30 11:34 UTC
