### ISSUE TITLE
YAML cannot load example from its own web site [rt.cpan.org #16975]

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/yaml-pm#51] opened 2014-08-14 06:41 UTC
https://rt.cpan.org/Ticket/Display.html?id=16975

```
YAML 0.39 does not correctly import the invoice exampel given in 2.27 on the YAML.org web site:

perl -MYAML -MData::Dumper -e 'print Dumper(YAML::LoadFile("ex-2.27-invoice"))'
--- !perl/YAML::Error
code: YAML_LOAD_ERR_NO_CONVERT
msg: "Can't convert implicit 'XXX' node to explicit '<tag:clarkevans.com,2002:invoice>' node"
line: 26
document: 1
...
 at -e line 1
```

**Comment by perlpunk** [comment] 2019-05-14 19:31
This is a problem with plain multiline scalars. The error message is currently:
```
  YAML Error: Expected separator '---'
     Code: YAML_PARSE_ERR_NO_SEPARATOR
     Line: 27
     Document: 2
```

It is a duplicate of #47

**Closed by perlpunk** 2019-05-14 19:31 UTC
Labels: Important, Migrated From RT
